version: "3"
services:
  api:
    image: czht1118/api:${API_IMAGE_TAG}
    container_name: api
    ports:
      - "${HTTP_LISTEN}:${HTTP_LISTEN}"
    volumes:
      - "${DATA_IMAGE}:${DATA_IMAGE}:rw"
      - "/data/console/:/data/console:rw"
    restart: always
    entrypoint: [ "/data/console/api", "--http-listen", ":${HTTP_LISTEN}" ]
    environment:
      TZ: "$TZ"
      MYSQL_ENDPOINT: "${MYSQL_ENDPOINT}"
      REDIS_ENDPOINT: "${REDIS_ENDPOINT}"
      API_IMAGE_TAG: "${API_IMAGE_TAG}"
    networks:
      - default

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - "/data/:/data/:rw"
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

  php:
    image: php-${PHP_VERSION}
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    ports:
      - "${PHP_PORT}:9000"
    expose:
      - 9000
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql5:
    image: mysql:${MYSQL5_VERSION}
    container_name: mysql5
    ports:
      - "${MYSQL5_HOST_PORT}:3306"
    volumes:
      - ${MYSQL5_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql5:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL5_ROOT_PASSWORD}"
      TZ: "$TZ"

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: [ "redis-server", "/etc/redis.conf" ]
    environment:
      TZ: "$TZ"
    networks:
      - default

networks:
  default:
